//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PandaTechEShop.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PandaTechEShop.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account successfully created..
        /// </summary>
        internal static string AccountCreatedMessage {
            get {
                return ResourceManager.GetString("AccountCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Failed to create account. Please try again..
        /// </summary>
        internal static string AccountCreationFailedErrorMessage {
            get {
                return ResourceManager.GetString("AccountCreationFailedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed. Please check your username and password..
        /// </summary>
        internal static string AuthenticationFailureErrorMessage {
            get {
                return ResourceManager.GetString("AuthenticationFailureErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Account....
        /// </summary>
        internal static string LoadingDialogCreatingAccountMessage {
            get {
                return ResourceManager.GetString("LoadingDialogCreatingAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging In....
        /// </summary>
        internal static string LoadingDialogLoggingInMessage {
            get {
                return ResourceManager.GetString("LoadingDialogLoggingInMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Failed to login. Please try again..
        /// </summary>
        internal static string LoginFailedUnknownErrorMessage {
            get {
                return ResourceManager.GetString("LoginFailedUnknownErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string SignInButtonText {
            get {
                return ResourceManager.GetString("SignInButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in to your account.
        /// </summary>
        internal static string SignInH1BlurbText {
            get {
                return ResourceManager.GetString("SignInH1BlurbText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email me about special pricing deals.
        /// </summary>
        internal static string SignupAllowMarketingText {
            get {
                return ResourceManager.GetString("SignupAllowMarketingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        internal static string SignupButtonText {
            get {
                return ResourceManager.GetString("SignupButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your account.
        /// </summary>
        internal static string SignupH1BlurbText {
            get {
                return ResourceManager.GetString("SignupH1BlurbText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep me signed in.
        /// </summary>
        internal static string SignupKeepSignedInText {
            get {
                return ResourceManager.GetString("SignupKeepSignedInText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Sign in .
        /// </summary>
        internal static string SignupSignInButtonText {
            get {
                return ResourceManager.GetString("SignupSignInButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account? .
        /// </summary>
        internal static string SignupSignInExistingAccountBlurbText {
            get {
                return ResourceManager.GetString("SignupSignInExistingAccountBlurbText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please try again later..
        /// </summary>
        internal static string UnkownGenericErrorMessage {
            get {
                return ResourceManager.GetString("UnkownGenericErrorMessage", resourceCulture);
            }
        }
    }
}
