//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PandaTechEShop.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PasswordResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PasswordResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PandaTechEShop.Resources.PasswordResources", typeof(PasswordResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string PasswordConfirmPlaceholderText {
            get {
                return ResourceManager.GetString("PasswordConfirmPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A password is required..
        /// </summary>
        internal static string PasswordEmptyValidationErrorMessage {
            get {
                return ResourceManager.GetString("PasswordEmptyValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and confirm password must match.
        /// </summary>
        internal static string PasswordMatchValidationErrorMessage {
            get {
                return ResourceManager.GetString("PasswordMatchValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have 1 digit.
        /// </summary>
        internal static string PasswordMinDigitCountValidationErrorMessage {
            get {
                return ResourceManager.GetString("PasswordMinDigitCountValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password minimum length is 8 characters.
        /// </summary>
        internal static string PasswordMinLengthValidationErrorMessage {
            get {
                return ResourceManager.GetString("PasswordMinLengthValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have 1 lowercase character.
        /// </summary>
        internal static string PasswordMinLowercaseCountValidationErrorMessage {
            get {
                return ResourceManager.GetString("PasswordMinLowercaseCountValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have 1 special character.
        /// </summary>
        internal static string PasswordMinSpecialCharacterCountValidationErrorMessage {
            get {
                return ResourceManager.GetString("PasswordMinSpecialCharacterCountValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have 1 uppercase character.
        /// </summary>
        internal static string PasswordMinUppercaseCountValidationErrorMessage {
            get {
                return ResourceManager.GetString("PasswordMinUppercaseCountValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot have any spaces.
        /// </summary>
        internal static string PasswordMinWhitespaceCountValidationErrorMessage {
            get {
                return ResourceManager.GetString("PasswordMinWhitespaceCountValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordPlaceholderText {
            get {
                return ResourceManager.GetString("PasswordPlaceholderText", resourceCulture);
            }
        }
    }
}
